### ISSUE TITLE
Getting "FastifyError [Error]: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.2.1' is installed" error when trying to upgrade to fastify v4.2.1

### ISSUE THREAD

**Issue by varunkamra** [fastify/help#722] opened 2022-07-20 11:36 UTC
## I am trying to upgrade fastify version in my project from 3.29.0 to 4.2.1 but I am getting the following error:

```
FastifyError [Error]: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.2.1' is installed
     at Object.checkVersion (/var/www/node_modules/fastify/lib/pluginUtils.js:118:11)
     at Object.registerPlugin (/var/www/node_modules/fastify/lib/pluginUtils.js:133:16)
     at Boot.override (/var/www/node_modules/fastify/lib/pluginOverride.js:28:57)
     at Plugin.exec (/var/www/node_modules/avvio/plugin.js:79:33)
     at Boot.loadPlugin (/var/www/node_modules/avvio/plugin.js:272:10)
     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
   statusCode: 500
 }
``` 
I got this error by just updating fastify version requirement in the package.json and then tried to test it again after adding dependency to `@fastify/static` with version `6.4.0` but still got the above error. Any idea why this is failing?

Here's the package.json dependencies which is using fastify 3.29.0 currently:

```js
"dependencies": {
    "@fastify/swagger": "^6.1.0",
    "axios": "^0.27.2",
    "deepmerge": "^4.2.2",
    "dotenv": "^16.0.0",
    "express": "^4.18.1",
    "fastify": "^3.29.0",
    "fastify-decorators": "3.12.0",
    "http-status-codes": "2.2.0",
    "jwt-decode": "3.1.2",
    "node-mocks-http": "^1.11.0",
    "nodemon": "^2.0.16",
    "qs": "^6.10.3",
    "ts-node": "^10.7.0",
    "winston": "^3.7.2",
    "winston-daily-rotate-file": "^4.7.1"
  },
  "devDependencies": {
    "@fastify/redis": "^5.0.0",
    "@tsconfig/node16-strictest-esm": "^1.0.2",
    "@types/jest": "^27.5.2",
    "@types/node": "^17.0.27",
    "@types/qs": "^6.9.7",
    "@typescript-eslint/eslint-plugin": "^5.22.0",
    "@typescript-eslint/parser": "^5.22.0",
    "eslint": "^8.17.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard": "^17.0.0",
    "eslint-config-typescript": "^3.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-n": "^15.2.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-promise": "^6.0.0",
    "jest": "^28.1.0",
    "prettier": "^2.6.2",
    "ts-jest": "^28.0.5",
    "typescript": "^4.6.4"
  }
````

## Your Environment

- *node version*: 16
- *fastify version*: >=3.29.0
- *os*: Linux

**Comment by Asjas** [comment] 2022-07-20 11:41
You are not updating `@fastify/swagger` with `fastify`. You need to update `@fastify/swagger` to `v7.x` to support Fastify v4.

Duplicate of issues https://github.com/fastify/help/issues/712 and https://github.com/fastify/help/issues/707

**Comment by Asjas** [comment] 2022-07-20 11:46
>I got this error by just updating fastify version requirement in the package.json. 
> Any idea why this is failing?

You aren't updating `@fastify/swagger`. You need to update `@fastify/swagger` to `v7.x` to support Fastify `v4.x`.

Duplicate of issues https://github.com/fastify/help/issues/712 and https://github.com/fastify/help/issues/707

**Closed** 2022-07-20 12:16 UTC
Labels: help wanted

**Comment by varunkamra** [comment] 2022-07-21 18:14
Thank you, that fixed it!
