### ISSUE TITLE
Fastify docs build

### ISSUE THREAD

**Issue by marcodev86** [fastify/help#622] opened 2022-02-06 13:49 UTC
## 💬  Question here 

Hi guys, I have tried to build fastify-docs from fastify-website repo, in order to start live-server.

build:process-releases was stopped with the error :  

```js
[Error: ENOENT: no such file or directory, open 'build-temp/releases/releases.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'build-temp/releases/releases.json'
}
````

I haven't found any information on how to populate the releases.json file 

## Your Environment

- *node version*: 14.18.3
- *os*: Linux

**Comment by luisorbaiceta** [comment] 2022-02-06 14:09
Are you just running the `build:process-releases` command before starting the live server?

**Comment by marcodev86** [comment] 2022-02-06 16:58
Thanks luisorbaiceta,

I have read the packages.json content, and I have executed many scripts, `npm run buid`, `npm run start:dev` and also the single steps of npm build,  but unfortunately the results hasn't changed.

Into build-temp/releases, I have some directories with hash name, but no trace of the required json file.

I attached script output
[fastify-website.log](https://github.com/fastify/help/files/8010655/fastify-website.log)

**Comment by luisorbaiceta** [comment] 2022-02-06 18:00
If you run `build:get-releases`, does the `releases.json` file get generated in `build-temp/releases/releases.json`?

**Comment by marcodev86** [comment] 2022-02-06 20:57
It would appear that `build:get-releases` doesn't always work perfectly.
Running `build` or `start:dev` does not seem to create releases.json.

I fixed it by doing a `build-cleanup` and then running `build-get-releases` twice more

I attached log, it may be useful

[1-start_dev.log](https://github.com/fastify/help/files/8011213/1-start_dev.log)
[2-ok.log](https://github.com/fastify/help/files/8011214/2-ok.log)

**Comment by luisorbaiceta** [comment] 2022-02-06 21:13
Sorry. I can't reproduce the error

**Comment by luisorbaiceta** [comment] 2022-02-07 09:45
Closing this. Cloning the repo as is, and running it in the described environment is working as expected. Please note that our current build process is under discussion and might change in the future.

**Closed by luisorbaiceta** 2022-02-07 09:45 UTC
Labels: help wanted
