### ISSUE TITLE
Migrating express + react + webpack application to fastify

### ISSUE THREAD

**Issue by jainChetan81** [fastify/help#989] opened 2024-02-01 14:21 UTC
## 💬  Question here 

I am trying my full stack application of express, webpack and react to use fastify and while the application from node side isn't large enough, I am getting multiple issues some of which are not mentioned in the docs at all.
Like the current repo I have shared is redirecting all the urls to 404 which is very confusing to understand.
Please would like to understand what is going on here
Source code of server here

```js
export default async (app: Express, fastifyApp: FastifyInstance, faviconName: string) => {
	// Use helmet to secure Express with various HTTP headers
	fastifyApp.register(require("@fastify/helmet"), {
		contentSecurityPolicy: false,
		global: true
	});

	// Prevent HTTP parameter pollution
	app.use(hpp());
	await fastifyApp.register(fastifyExpress);
	// Compress all requests
	await fastifyApp.register(require("@fastify/compress"), { global: false });

	// Use for http request debug (show errors only)
	app.use(favicon(path.resolve(process.cwd(), `public/${faviconName}.ico`)));
	// fastifyApp.register(require("fastify-favicon"), {
	// 	path: path.resolve(process.cwd(), `public`),
	// 	name: `favicon.ico`
	// });
	app.use(express.static(path.resolve(process.cwd(), "public")));

	// Enable dev-server in development
	if (__DEV__) devServer(fastifyApp);

	// Use React server-side rendering middleware
	app.get("*", ssr);

	fastifyApp.listen(config.PORT, config.HOST, (error) => {
		if (error) console.error(`==> 😭  OMG!!! ${error}`);
	});
};

````

Github : https://github.com/jainChetan81/fastify-webpack

## Your Environment

- *node version*: 20
- *fastify version*: >=4.26.0
- *os*: Mac

**Comment by mcollina** [comment] 2024-02-01 14:31
How can I reproduce the problem in your repo?

A few notes:

1. use `@fastify/static` for serving files
2. use the same module to serve the favicon

**Comment by jainChetan81** [comment] 2024-02-02 06:42
npm install && npm run dev

**Comment by jainChetan81** [comment] 2024-02-02 06:45
I updated the repo to use `@fastify/static` to server files, right now its serving stringifiedmhtml like shown in the image,
checkout `server/index.ts` file , which is the entry point for server file
<img width="1440" alt="Screenshot 2024-02-02 at 12 14 38 PM" src="https://github.com/fastify/help/assets/38555207/6edf2b71-0130-4ef7-ae09-9de05375535f">

**Comment by Uzlopak** [comment] 2024-02-02 07:00
When you see the sourcecode of the html files, than this is because you dont send the Content-Type headers properly. 

So here: 

https://github.com/jainChetan81/fastify-webpack/blob/d18afeca2b9335865ed7ef084a698c8bbbee6ddc/src/server/ssr.tsx#L93

You would add a `.header('content-type', 'text/html; charset=utf-8');`

**Comment by jainChetan81** [comment] 2024-02-02 11:36
Yeah thanks, that worked, actually I am trying to create a repro close to my actual application, will clean up some bit and tryu again...

**Comment by jainChetan81** [comment] 2024-02-02 16:20
Found one issue, when I am using fastify like , this breaks the server, and this doesn't worrk when I replace `("*")` with `("/")`
```
fastifyApp.get("*", (req, rep) => {
	ssr(req, rep);
});
```
have updated the original repo to use fastify completely and this is where I am stuck
https://github.com/jainChetan81/fastify-webpack/blob/main/src/server/appServer.ts

**Comment by Uzlopak** [comment] 2024-02-02 16:27
Please use clear language. What does it mean "breaks the server"? 

I actually see here a different issue: 
ssr is an async function. your handler is sync. 
Without even cloning your repo or testing I would say this is a bug.

I would solve it like this.

```js
fastifyApp.get("*", async (req, rep) => {
	await ssr(req, rep);
        return rep;
});
```

Or better make ssr return the reply and then just call return ssr(req, rep)

**Comment by jainChetan81** [comment] 2024-02-02 18:28
I meant app crashed, with no error logging
<img width="846" alt="Screenshot 2024-02-02 at 11 57 55 PM" src="https://github.com/fastify/help/assets/38555207/3c443147-1801-4e85-b31c-be0709a591af">

**Comment by jainChetan81** [comment] 2024-02-02 18:31
updated the demo, still facing same issue

**Comment by Uzlopak** [comment] 2024-02-02 18:48
Of course it will not work properly when fastify static is installing a catch all and you are also providing a catch all. 
https://github.com/jainChetan81/fastify-webpack/pull/1

**Comment by Uzlopak** [comment] 2024-02-02 19:06
I see you merged my PR. is your issue solved?

**Comment by jainChetan81** [comment] 2024-02-02 19:17
Yes, Thank you that worked...
Right now trying to figure out why the compiled css is 0kb, not sure this is a fastify issue

**Closed** 2024-02-03 15:42 UTC
Labels: help wanted
