### ISSUE TITLE
Detecting an aborted connection before a reply is sent

### ISSUE THREAD

**Issue by WesSouza** [fastify/help#773] opened 2022-10-17 14:16 UTC
I have a situation where I delay a server response until an event occurs. The client that started the request might cancel it due to inactivity or a timeout, and I'd like to know when that happens but can't find an event that would give me that information.

This is a simplified version of what I want to achieve:

```js
fastify.post(
  "/wait",
  (request, reply) => {
    const controller = new AbortController();
    thisWillDelay(controller.signal).then(() => { reply.send("done") })

    request.something.on("close", () => { controller.abort() } )
  }
);

```

I've tried every event listed on `request.raw`, `request.socket` and `response.raw` and couldn't get a concise event when the connection is closed by the client.

Am I misinterpreting something, or missing where the event is called?

## Your Environment

- *node version*: 16.17.1
- *fastify version*: 4.6.0
- *os*: macOS

**Comment by climba03003** [comment] 2022-10-17 16:16
> Am I misinterpreting something, or missing where the event is called?

AFAIK, there is no reliable way to inspect such case.
However, you can simply listen the `error` event of `request.socket` which should do the same.

**Comment by metcoder95** [comment] 2022-10-17 21:42
This case is quite tricky, you need to basically listen at the `end` event triggered by the underlying `socket` instance, and de-register once you finish your execution and no longer interested in the event (otherwise will give you the `end` event because you already replied to the user).

I made the [fastify-racing](https://github.com/metcoder95/fastify-racing) plugin exactly for that purpose, so you can subscribe or await in case a request has been aborted by the client. Hope it helps 🙂

**Comment by simoneb** [comment] 2023-01-12 11:10
Duplicate of https://github.com/fastify/help/issues/577.

I see this request coming up quite a bit, probably an opportunity for documentation.

**Comment by simoneb** [comment] 2023-02-03 11:45
I think this can be closed

**Closed** 2023-02-03 12:00 UTC
Labels: help wanted
