### ISSUE TITLE
intermittent 500 errors on manual errors thrown

### ISSUE THREAD

**Issue by paul590** [fastify/help#227] opened 2020-07-30 22:00 UTC
Hello,

I recently started using your library and I am encountering a weird issue. I am using typescript and graphql. Whenever I throw an error in the format of: new Error("This is an error"). The graph ql ui provides the following:

"error": {
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Internal Server Error"
  }

the strange part happens when i press the run button again on the ui, the proper error message is displayed. This 500 error only appears the first time I try to run a query that throws an error, subsequent calls do not throw this error. I was using Apollo server before and everything worked as expected. Can you please provide some assistance?

Thank you in advance!

**Comment by RafaelGSS** [comment] 2020-07-31 03:53
Can you provide a reproduction repository/code?

**Comment by paul590** [comment] 2020-07-31 20:09
Hi Rafael, sure thing! I added you to the repo I created https://github.com/paul590/toSendGraphQL

Also, I added a readme where i explain what issues I am seeing. If you would like me to add other developer please let me know. Thank you for your help!

**Comment by Eomm** [comment] 2020-07-31 20:11
The link is broken. Is the repo public?

**Comment by paul590** [comment] 2020-07-31 21:05
Can you try again please, the repo is private and i added you to it

**Comment by Eomm** [comment] 2020-08-01 09:07
It would be better a public repo.

> you will see 500 error. On code remove the errorHandler: false it throws correct format on manual error but format changes when system throws error such as when using an incorrect function like test2(code: "test").

Anyway, I think you should define an `errorHandler` function:
- `false` would mean you are using the fastify standard error handler
- `true` you are using the [GrapQL standard error handler](https://github.com/mcollina/fastify-gql/blob/8f674b0f55b30a54e80882cd522e321705ffc7b6/lib/errors.js)
- a function would mean you can support both

**Comment by paul590** [comment] 2020-08-03 13:27
@Eomm Thank you for your response! I understand I can use this approach, however, is there a reason why when using false we see a 500 error at first and then on the second call the appropriate response? Please let me know. Thank you!

**Comment by paul590** [comment] 2020-08-03 17:15
Hi @Eomm I implemented a simple error handler and unfortunately, the 500 error persisted. 

```
this.server.setErrorHandler((error, request, reply) => {
            console.log(error);
            console.log(request);
            console.log(reply);
            reply.send(error);
       })
```

**Comment by RafaelGSS** [comment] 2020-08-03 19:48
Hi @paul590 I'll take a look, but after a fast investigation, sounds like a bug inside cache of GQL. I'll take a closer look more later

**Comment by Eomm** [comment] 2020-08-03 20:19
I can't debug it right, now.

The @RafaelGSS 's suggestion could help to spot the issue: you could try to [disable the cache](https://github.com/mcollina/fastify-gql#appgraphqldefineloadersloaders) to check it rapidly 👍

**Comment by paul590** [comment] 2020-08-03 21:56
Hi @RafaelGSS and @Eomm thank you for your help with this. That would make sense as to why we see the second result as intended. What I am failing to understand is why would the first error would be in the format of: 

{
  "error": {
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Internal Server Error"
  }
}

if the caching is acting properly shouldnt it be the same error for the second error? 

Also, when creating a custom error handler I noticed the object I create is wrapped by an error object. for example { error: { new object variables } } is there a way to remove this error object wrap? Thank you for all your help!

**Comment by RafaelGSS** [comment] 2020-08-05 01:34
@paul590 I just changed on `fastify-gql/index.js`:

```diff
- const lru = buildCache(opts)
+ const lru = buildCache({ ...opts, cache: false })
```
and works fine (the request did not change the result). So, maybe you can define `cache` at [here](https://github.com/mcollina/fastify-gql/blob/master/index.d.ts#L112) to you use in your application without transpilation error.

**Comment by RafaelGSS** [comment] 2020-08-05 01:35
Btw, is good to create an issue on this plugin to inform the behaviour of the cache.

**Comment by paul590** [comment] 2020-08-07 21:47
@RafaelGSS Thank you for letting me know this information. The link that your provided me with didnt seem to show me where I would the cache. would I add this information when initializing the server? If the cache is the issue, is there a way to only remove the cache on errors or would this be a plugin issue? Thank you again!!

server.register(GQL, {
        schema,
        jit: 1,
        path: "/",
        graphiql: "playground",
    })

**Comment by RafaelGSS** [comment] 2020-08-07 22:08
Do you will use:
```diff
server.register(GQL, {
  schema,
  jit: 1,
  path: "/",
  graphiql: "playground",
+ cache: false,
})
```

However, you are using typescript and could have an error because  `cache` property is not defined on the link that I sent. An workaround is:

```diff
server.register(GQL, {
  schema,
  jit: 1,
  path: "/",
  graphiql: "playground",
+ cache: false,
+ } as any)
```

**Comment by mcollina** [comment] 2020-08-08 13:23
@RafaelGSS can you send a PR to fix the cache issue?

**Comment by paul590** [comment] 2020-08-08 13:38
@RafaelGSS Thank you for your quick response. Is there a way to remove the cache only for errors? It would be great to have the cache ability still available for all other requests.

Also, when creating a custom error handler I noticed the object I create is wrapped by an error object. for example { error: { new object variables } } is there a way to remove this error object wrap? Thank you for all your help!

**Comment by RafaelGSS** [comment] 2020-08-09 17:28
> Is there a way to remove the cache only for errors

Hey @paul590. I don't read all the source code, but I think removing the cache only for errors is not possible (for now). @mcollina should know more about it.

> when creating a custom error handler I noticed the object I create is wrapped by an error object. for example { error: { new object variables } } is there a way to remove this error object wrap? 

This is the default error handler on fastify, you can change it [here](https://www.fastify.io/docs/v1.13.x/Server/#seterrorhandler)

**Comment by mcollina** [comment] 2020-08-09 19:37
I don't understand what the bug is and a repro is missing. Feel free to send a PR.

**Comment by paul590** [comment] 2020-08-10 21:19
@RafaelGSS  Thank you for your help! removing the cache does allow me to add a custom error and constantly provides me with the same error every time i run the query. Regarding the error itself, even though I am generating a custom error I still see it is created with the error {... custom variables go here } format. Is it possible to change the name of the error variable within the custom error handler? Thank you again!

**Comment by paul590** [comment] 2020-08-10 21:23
@mcollina Thank you for your reply, the issue is that when running a query that returns an error using the cache, we will see a 500 error at first. The second time I run the error message is different. It is not cachin the error properly. I have added you to the project which i under this link: https://github.com/paul590/toSendGraphQL

**Comment by RafaelGSS** [comment] 2020-08-10 21:39
>> This is the default error handler on fastify, you can change it here

> Is it possible to change the name of the error variable within the custom error handler? Thank you again!

What do you already try?

**Comment by mcollina** [comment] 2020-08-11 11:35
This should be fixed in https://github.com/mcollina/fastify-gql/pull/248, please check.

**Closed** 2020-08-11 16:34 UTC

**Comment by paul590** [comment] 2020-08-11 21:35
@mcollina @RafaelGSS  thank you for the quick response and fix! now i see the error object instead of the 500 error. the last issue that i am seeing is related to the error object itself. when i first get the error it looks as follows:

{
  "error": {
    "data": null,
    "errors": [
      {
        "message": "error message thrown",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "path": [
          "test"
        ]
      }
    ]
  }
}

however, if i run the same query again I see the error as below:

{
  "data": null,
  "errors": [
    {
      "message": "error message thrown",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "test"
      ]
    }
  ]
}

Notice how there is an error object that wraps the actual error at first but then disappears with the cache of the error. The same issue happens when using custom errors. is there a way to remove this error wrapping? also, would you like me to open a new case for this? Thank you so much for your help!!

**Comment by RafaelGSS** [comment] 2020-08-12 11:54
Hey, @paul590 I think is better you open another issue for it, because we are talking about 2 problems (related). Don't forget of reproduction code - open source is better because other contributors/users could check it and help them.

**Comment by paul590** [comment] 2020-08-12 13:21
@RafaelGSS will do thank you for your help!!

**Comment by paul590** [comment] 2020-08-12 18:13
@RafaelGSS @mcollina it seems with the new update the custom error handler is not being called. I tried clearing the cache and cookies and I am unable to see my new error handler. I have updated the repo with this issue. Thank you again!!

**Comment by paul590** [comment] 2020-08-12 18:15
I have also opened the project as request to public
