### ISSUE TITLE
Fastify Typescript does not recognize GET PUT POST, etc

### ISSUE THREAD

**Issue by isabellabogado** [fastify/help#963] opened 2023-11-17 20:20 UTC
I created a new project with Fastify, bare and using the CLI. In both cases it does not recognize any type... 

Anyone could do this?
![image](https://github.com/fastify/help/assets/94136420/020499d6-e2b8-41b4-b982-3ee9271c9f12)

- *node version*: v18.2.0
- *os*: Mac

Package Json
`"dependencies": {
    "@fastify/autoload": "^5.8.0",
    "@fastify/sensible": "^5.5.0",
    "fastify": "^4.24.3",
    "fastify-cli": "^5.9.0",
    "fastify-plugin": "^4.5.1"
  },
  "devDependencies": {
    "@types/node": "^20.9.1",
    "@types/tap": "^15.0.11",
    "c8": "^8.0.1",
    "concurrently": "^8.2.2",
    "fastify-tsconfig": "^2.0.0",
    "tap": "^16.1.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },`

**Comment by Asjas** [comment] 2023-11-17 22:01
You should assign the Fastify type to the function argument, you aren't doing that. You have other types defined

**Comment by mcollina** [comment] 2023-11-18 21:49
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by RagingLink** [comment] 2023-11-20 16:33
Having the same issue here, some methods like `.addHook` are not being recognised as well

My steps used to reproduce the issue:
```
yarn init -y
yarn add fastify && yarn add -D @types/node typescript
yarn run tsc --init
```
Change `"target": "es2016"` in `tsconfig.json` to `"es2020"` per https://fastify.dev/docs/latest/Reference/TypeScript/#getting-started
Create `index.ts` (from the getting started section in the above link)
```ts
import fastify from 'fastify'

const server = fastify()

server.get('/ping', async (request, reply) => {
  return 'pong\n'
})

server.listen({ port: 8080 }, (err, address) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }
  console.log(`Server listening at ${address}`)
})
```
And then typescript starts  the complaints
![image](https://github.com/fastify/help/assets/15198000/136a3dca-2751-42e5-8e87-baf5710283dc)

Versions:
```
Node: v16.20.2
Yarn: 1.22.19

fastify: "^4.24.3"
@types/node: "^20.9.2",
typescript: "^5.2.2"
```

**Comment by mcollina** [comment] 2023-11-20 19:21
I can't reproduce by running `npx tsc` on that repo, everything builds and run correctly.

**Comment by RagingLink** [comment] 2023-11-20 22:31
> I can't reproduce by running `npx tsc` on that repo, everything builds and run correctly.

For me, the issue was just the errors in the (VS-code) editor, the code built just fine without errors.

I wanted to be sure that it wasn't an extension issue, so I created a new profile (had to update my VS code), and now I can't reproduce it anymore on either profile, so I'm not really sure anymore! 
Appears to be related to VS code rather than Fastify+TS (for me at least), and updating/reloading 'fixed' the issue.

**Comment by climba03003** [comment] 2023-11-21 03:15
Closing, it apparently the issue on VSCode.
Sometimes, VSCode need to reload the extension if you change `node_modules`.

**Closed by climba03003** 2023-11-21 03:15 UTC
Labels: help wanted
