### ISSUE TITLE
routes prefix with autoload is not working

### ISSUE THREAD

**Issue by Mohamedsobhy292** [fastify/help#717] opened 2022-07-15 18:27 UTC
#### What are you trying to achieve, or the steps to reproduce?

I have a routes folder I load it to the app with autoload plugin I have a problem adding prefix to all routes

my routes/users.ts file
```js
import { FastifyInstance, FastifyPluginOptions } from 'fastify'
import fp from 'fastify-plugin'

const userRoutes = (
    server: FastifyInstance,
    options: FastifyPluginOptions,
    done: () => void
) => {
    server.get('/users', {}, (request, reply) => {
        reply.send({ hello: 'world' })
    })

    done()
}

export default fp(userRoutes)

```

and  in my app.ts I do

```js
    dir: join(__dirname, 'routes'),
    options: { prefix: 'api/v1' },
})
```

but it's not working and I still get `/users` instead of `/api/v1/users`

**Comment by Asjas** [comment] 2022-07-16 14:29
> Route Prefixing option
> 
> If you pass an option with the key prefix with a string value, Fastify will use it to prefix all the routes inside the register, for more info check [here](https://www.fastify.io/docs/latest/Reference/Routes#route-prefixing).
> 
> Be aware that if you wrap your routes with [fastify-plugin](https://github.com/fastify/fastify-plugin), this option will not work (there is a [workaround](https://www.fastify.io/docs/latest/Reference/Routes#fastify-plugin) available).

https://www.fastify.io/docs/latest/Reference/Plugins/#route-prefixing-option

@Mohamedsobhy292 The issue is happening because you are using `fastify-plugin`. If you remove it from the `users.ts`  file then it will set the `prefix` correctly.

![Screenshot 2022-07-16 at 16 23 46](https://user-images.githubusercontent.com/3828967/179358893-23270fc3-bd52-4763-9a43-7dc994a8028c.png)

**Comment by Mohamedsobhy292** [comment] 2022-07-16 15:33
@Asjas thank you it worked, but isn't routes should be used as plugins in order to work with autoload or what ?

**Comment by Asjas** [comment] 2022-07-16 15:38
>but isn't routes should be used as plugins in order to work with autoload or what

It is already a plugin. All routes in Fastify are plugins.

>Your routes, your utilities, and so on are all plugins.
https://www.fastify.io/docs/latest/Guides/Plugins-Guide/#register

`fastify-plugin` isn't used to create plugins, it's used to remove the default encapsulation that plugins have.

>When you build plugins for Fastify and you want that them to be accessible in the same context where you require them, you have two ways:
>
>  * Use the `skip-override` hidden property
>  * Use this module


https://github.com/fastify/fastify-plugin#fastify-plugin

**Comment by climba03003** [comment] 2022-07-16 16:32
I believe the answer already provided by @Asjas. Appreciate the helps
Closing the issue.

**Closed by climba03003** 2022-07-16 16:32 UTC

**Comment by Mohamedsobhy292** [comment] 2022-07-17 13:48
@Asjas thank you for your help
