### ISSUE TITLE
Write data continuously to the reply.raw element without closing the connection

### ISSUE THREAD

**Issue by MarianoFacundoArch** [fastify/help#635] opened 2022-02-22 12:44 UTC
I have tried several ways of doing so, and there's no way i can achieve that with the exact same modules and code I use to do so with an express middleware.
The exact same code within an express middleware with compatibility with fastify-express works, but when I use the exact same thing with fastify, after the first reply.raw.write, it closes the client connection.

How can I avoid that ?

**Comment by MarianoFacundoArch** [comment] 2022-02-22 16:16
Here goes a very interesting conclusion, I think a found a bug.

If I put the following :
`
      reply.raw.writeHead(200, {
        "Content-Type": "video/mp4",
      });`
The connection gets closed after the first write.
If I don't, it works as expected. This only happens while on fastify without middlewares, so there might be a bug. When I use fastify-express and the old middleware, that does literally a res.writeHead exactly the same and the rest are the exact same writes, it does not happen.

Is there a missing config I am forgetting? Or is there a bug?

**Comment by MarianoFacundoArch** [comment] 2022-02-22 17:21
The problem seems to be more complex, the subsequent .writes while on fastify somehow break the response, or encoding, or order of data sent.

**Comment by MarianoFacundoArch** [comment] 2022-02-22 17:27
The problem is while doing multiple writes of raw data (mp4), so chunked transfer-enconding, but it's not working, somehow fastify is breaking it up and I can't find how to disable that behaviour withotu having to go through a middleware and fastify-express

**Comment by MarianoFacundoArch** [comment] 2022-02-22 18:52
More updates: If I use middie and create a middleware and send the response there from res.write, it works.

There must be something in Fastify breaking the normal behaviour of reply.raw.send after the first sending.
Any idea on how to fix this?

**Comment by jsumners** [comment] 2022-02-22 18:57
Without a minimal reproduction we are unable to even venture guesses.

**Comment by MarianoFacundoArch** [comment] 2022-02-23 10:26
Hi,
The reproduce scenarios is the following:

You start the response of the request with
reply.raw.writeHead(200, { "Content-Type": "video/mp4", });


Then you start sending an mp4 file with multiple reply.raw.write (Buffer part)

When it's through fastify without middlewares, it fails after the second sent chunk, with middie or fastify-express it works perfectly.

So fastify must be attaching a handler or whatever that is corrupting it

**Comment by climba03003** [comment] 2022-02-23 10:42
I don't know how to reproduce your case.

Here is the code I have tried. But it hold the connection correctly.
It only ended when I call `reply.raw.end()`
```js
const Fastify = require("fastify", { logger: true });

const fastify = Fastify();

fastify.get("/", function (_, reply) {
  reply.raw.writeHead(200, { "Content-Type": "text/plain" });
  const buf = Buffer.alloc(2000, "s");
  reply.raw.write(buf);
  reply.raw.write(buf);
});

fastify.listen(3000);
```

**Comment by jsumners** [comment] 2022-02-23 13:25
Closing due to lack of cooperation. You are welcome to re-open if you are willing to provide a minimal reproduction.

**Closed by jsumners** 2022-02-23 13:25 UTC
