### ISSUE TITLE
Documentation for newest Typescript bindings

### ISSUE THREAD

**Issue by ouifi** [fastify/help#251] opened 2020-08-26 00:35 UTC
## 🐛 Bug Report

I started using Fastify with Typescript a couple of weeks ago, I think the Fastify version was 3.2.0. I found the documentation on using with Typscript useful, but as of upgrading to 3.2.1 (and 3.3.0) , Fastify Plugin is being flagged by my linter as `@deprecated` with a recommendation to see FastifyRegister.

For a brand new project, I don't want to start using something that has already been marked as deprecated, even it still works and will be supported for a couple more minor releases. 

Will there be/when will there be new documentation, either on how to migrate to the newest types, or how to build something from scratch using the new types?

https://www.fastify.io/docs/latest/TypeScript/#register was not helpful, as it uses the same pattern shown below. 

## To Reproduce

```ts
import fastify from "fastify";
import { FastifyInstance, FastifyPlugin } from "fastify";

const test: FastifyPlugin<{
    echo?: string
}> = function (instance: FastifyInstance, opts, done): void {

    interface TestEchoParams {
        echo?: string
    }

    instance.get<{
        Params?: TestEchoParams
    }>("/test/:echo", (request, reply) => {
        reply.send({
            echo: request.params.echo || opts.echo || "received...something"
        });
    });

    done();
};

const Server = fastify();
Server.register(test);
Server.listen(9000, (err, address) => {
    if (err) {
        process.exit(1);
    }
});
```

## Your Environment

- *node version*: 14.8.0
- *typescript*: 4.0.2
- *fastify version*: 3.2.1
- *os*: Windows

**Comment by mcollina** [comment] 2020-08-26 10:17
cc @fox1t @Ethan-Arrowood

**Comment by fox1t** [comment] 2020-08-26 14:23
Hi @ouifi I am trying to reproduce your issue, without success.
<img width="872" alt="image" src="https://user-images.githubusercontent.com/1620916/91295663-b6bce000-e79b-11ea-8414-707db0708c07.png">

As you can see the only "lint" issue I have is related to a possibly undefined value.

**Comment by ouifi** [comment] 2020-08-26 15:39
https://github.com/ouifi/witty-name-bp

**Comment by ouifi** [comment] 2020-08-26 15:42
The origin of this is 

https://github.com/fastify/fastify/blob/master/types/plugin.d.ts

**Comment by fox1t** [comment] 2020-08-26 15:44
Which file written by you is generating that issue? I've just downloaded the repo, opened it in vscode and built without issue.

**Comment by fox1t** [comment] 2020-08-26 15:45
Ok nevermind, I've found it: `routes/test.ts`

**Comment by ouifi** [comment] 2020-08-26 15:47
Yep. Thanks for looking into this with me! I like fastify a lot and I think this team and the work they do is awesome. I want to stay abreast of the best practices and continue using fastify for a long time. :)

**Comment by fox1t** [comment] 2020-08-26 15:48
Thanks for reporting this. We will look further into this. Meanwhile. to fix this issue and to be future proof change that line to:
```ts
const test: FastifyPluginCallback<{
    echo?: string
}> = function (instance: FastifyInstance, opts, done): void {
```

**Comment by ouifi** [comment] 2020-08-26 15:50
Got it. Glad that the fix is simple.

**Comment by fox1t** [comment] 2020-08-26 15:55
Reference, this was done in this PR: https://github.com/fastify/fastify/pull/2350

@Ethan-Arrowood, I am trying to figure out the rationale behind this deprecation decision, but I can't get it. Do you remember where the union type broke the `register` one (@lundibundi said this "I couldn't get TS to properly infer types for async versions of functions")?

**Comment by fox1t** [comment] 2020-08-26 15:56
Also for reference, v4.x.x of TS, inside VS Code, now renders deprecation like this:
```ts
```

**Comment by Ethan-Arrowood** [comment] 2020-08-26 15:57
Iirc this was done for the sake of moving users away from the general fastifyplugin definition and towards using one of the specific callback or async versions. I think it could be better documented though considering this experience

**Comment by fox1t** [comment] 2020-08-26 16:07
Yea but as far as I can see, today also the generic one is handled correctly by TS. Am I mistaken? It would be nice to have a demo repository that shows this issue.

**Comment by lundibundi** [comment] 2020-08-28 07:44
The issue is with typescript not inferring the types correctly when the overload like that is used. More info here https://github.com/fastify/fastify/pull/2350#issuecomment-650719201 and here is the [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwghgGwQIzgYwNZQLxQBQBQUxUAZgPbkBcUArgHYb3kDu9ANESagE40NNWHLsTTIaeCDx4B+GgFFp5HgEocAPigA3cgEsAJgTXZNOgwG4CBUJCgBBAM4h6aHPi4VqdRszadivPw+QkYaUAAKPOQAtroOEAA8Zvrqltbg0ABibvBIqJhQAD72Ti5WaOT0DsBQAOIAjG5wpa54pLQAXh00mexQyJ3d3oJsxpoA3iJQFVU1nm7jAL5TcCxwunODbZR9A10qBMsEM9V1AExNLfjtXT27g0Ej9GNQkyTTlafzuEtTNx3bcj3Lp9STSF5LA6LIA) by @Ethan-Arrowood that shows the issue with generic `FastifyPlugin` type.

There are type-tests in https://github.com/fastify/fastify/blob/master/test/types/plugin.test-d.ts that verify that inference works correctly. Specifically [callbacks](https://github.com/fastify/fastify/blob/2ab53e9cfb0185ddc65e792806ec5405e106a3da/test/types/plugin.test-d.ts#L25-L27) and [promises](https://github.com/fastify/fastify/blob/2ab53e9cfb0185ddc65e792806ec5405e106a3da/test/types/plugin.test-d.ts#L38-L40).
I've just tried to revert the types to generic FastifyPlugin and it still fails to infer plugin types correctly.

**Comment by mcollina** [comment] 2020-08-28 08:47
Is this related to https://github.com/fastify/fastify-plugin/pull/104?

**Comment by fox1t** [comment] 2020-08-28 09:30
@mcollina yes, the deprecation is because of that. 
@lundibundi thanks for linking the playground! That issue is related to the fact that we are using a union instead of an overload. Union plays really bad with functions in TS and it is a known limitation. Here you can find a [playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwDEAKRHHALnjQGtUcB3VAGngCNZKa7GWxXKiIGDAD8lAKLCcMAJTwAvAD54ANxxZgMymo3wAUKEiwEKdNjyESZTqloNmbDlVvdUW+AAUYOALZYAziAAPDrAynp6YHj+GPAA4gCMCvBQ-gCe6PAkyABeOZQYaQAOIDiIhCysufnOdoxySvAA3nrwbfBRqDFIZMlNAL6t7VD0UFixKHlWOJXVMnqDkdGxcQBMyakZYFmTNYUlZRVs1TZ1bgrKLe0dyz04fYPXu9OzeSyCwg2X-fP9QA) that implements the same logic using overloading. As you can see there are no issues at all. 
@Ethan-Arrowood do you think that this is better suited for our case? 

I really don't like forcing plugin developers to use two different types when it might be possible to infer them.

**Comment by lundibundi** [comment] 2020-08-28 09:48
@fox1t I completely agree that if we can make the types infer correctly without the need for separate types (or at least making their usage optional) it would be much better.

Here is how I defined the FastifyPlugin when I mentioned it in the comment before and it still doesn't work. Did I make a mistake here somewhere?
![Screenshot from 2020-08-28 12-43-13](https://user-images.githubusercontent.com/9109612/91547177-35e11e00-e92c-11ea-86c9-2304e42935fd.png)

**Comment by fox1t** [comment] 2020-08-28 10:05
The problem there is that it is used the interface representation of the functions instead of a function declaration. As far I as know overloading works only when using function declaration. Let me see if I can rewrite them as `declare function FastifyPlugin...`

**Comment by fox1t** [comment] 2020-08-28 10:09
Ok, since we are working with types and interfaces I found even a better solution: https://www.typescriptlang.org/play?#code/C4TwDgpgBAwghgGwQIzgYwNZQLxQBQBQUxUAZgPbkBcUArgHYb3kDu9ANESagE40NNWHLsTTIaeCDx4B+GgFFp5HgEocAPigA3cgEsAJgTXZNOgwG4CBUJCgBBAM4h6aHPi4VqdRszadivPw+QkYaUAAKPOQAtroOEAA8Zvrqltbg0ABibvBIqJhQAGT2Ti5WaOT0DsBQAOIAjG5wpa54pLQAXh00mexQyJ3d3oJsxpoA3iJQFVU1nm7jAL5TcCxwunODbZR9A10qBMsEM9V1AExNLfjtXT27g0Ej9GNQkyTTlafzuEtTNx3bcj3Lp9STSF5LA6LIA

Using an intersection instead of union triggers the function overload algorithm :)

**Comment by fox1t** [comment] 2020-08-28 10:14
Hmm, we still need to see if we can use it in the fastify codebase, though!

**Comment by fox1t** [comment] 2020-08-28 12:57
Ok, I finally got it! Sorry for pointing this out again, but it seemed too strange to me. 

@lundibundi our problem is a different one from @Ethan-Arrowood's playground shows and that confused me. In fastify typings, we are trying to implement two generic types that both happen to be functions, and then we want to "merge" them in only one generic type. On the other hand in the playground (and both of my examples), we have a function that accepts one or the other version of the function!

While we have the solution for the latter of the problems (function overload/intersection), it is not feasible to solve also the problem we have in allowing both generic types and therefore we need a union. 

I've putted together another [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwgY2ARigXigbwPaIroBcUARHgHYRkC+AUKJLIagExa4FLulnAB3PHXqim0AEJ5gAC3g9gAZ07yiGAD4sFbUfQD0eqAEsAZlHHKAhgCdo3IsoCulI1ShDrAa2Vu40mfTIVIrAUPaoaKRSsqqoytj4rCTkVDQMQZQhYUlsUf6xSpyJ2nyCwgz6hkaUYdYAJhDW5nhQjorQstBg1nhgygLQ1BB1zVBw0IqOtu4yRsgy2QpQMpbK4xA1YKvtdfQmzqiuNZbIyBBgwNFySYoA6kayeI7AAMIyKJ4AFOHAeTE3AEo+KkyFBNPwhKCcPQoLDjCZvkkAHQ-NAA3AwuFY2zAKY1H4opJoTGw2hQCAAG3aGKx2IguOs+ORPx0WIYDAMUAywB6FIp1QA5uZ3uSAB5GEKUM7GZQbJ4ChYmPBNAAqAGVjPj6o1RiYjAKpnZnsKOuAIIo9gdgEcoCczhcrgVFIiFH9rgpFECUtRQeCylCSfDPhQiaDqosiOjobS4Ti8RHUISFMS2eSqdBozGoHHGQngEmiKy4ezRJzZBKuXgGjLzJZPBsoCYegBbE1hCkjMAUywgAU9Zy7cRQF6WPlwE6eTifQNKvCkZyeSh4ASUAA0gfH1nnlEXy7XgeQcFIn0a1gA-KQAKLWHrWdGYAB8UAAbngjLt70-X++ANxiM1QAAgooIBSlOmKztuu4ruusKblBS4rvQn5QAACi2EoQAAPN+dQPn+jAAVcABiBycCOY4TmCQEgVKhHMCRBwAJKUMAjTtIcbjYBRFLjsgk4AGQ0aByCloY7TmlAjFgas5hCFAdSmCYjQbKEFi2pQIxDHUsqil2cwPFyqzAJUwoVhWS5qSKtijjKkwdCsoQDMsljPtA4ZPE0JjGaYIDmOAgoWhkWQAOIYNgqwiVAnz7AAXrFbqkVKq5jI48UIXuKGZrCwWhLORQMFiM5pbFMV4HgKVwCVKUnjeWW0OiUCBpYAiWIZMUlbayjASJAJlRVqXxQC9AVJygGHM+lhsconRhG51gUngli7JyWzWJYzb0uxwpTbapznKEfiyI2VpHMoKwzS04wKSg3a2CMsnVGx1gcdaVApeWVgTVNkl4PNi2KZQQqWJp2bmngFJucoEr2YEwShGFLHPa9NoRbRyDRXFCVSf4SXIEj7FEEclUlRlK5ZQe8ONuVBWBsV8X9ST8U1ae9WNc1rWGVjjODbFw2jVUZjqTY0D7FKb2ZK0LguG4dR4OalAAOROcqk67aOFJQAAtGZ0M+FMUDdAQFIQM2cOZGp5rJNJGPYGLnE1DzVXM1ycBRhyVQ1J9RnUvlIMjM7sW2tMIMgObWTTcAuQ47IeOcPbEuY+VTN87gYMMjU6F4M2mFIrYigQ25nwAgLxihHLCvK+4qvkm5NSmO40BtO5rGEw70X+7rNYQHpRDDMK8oyMNnIa4bNgbVtL3B9AocaSMs3IBrfGTvNig2hZ0i1w2QTNls1pwCb4eWyEADMiXMa3L1E1xJ3izaTvVa77tH+YVsACzn1KBNX+3dunW4D8hppxzJnDC7Q87g0hhAYutAgA) that wraps this up.

Have you searched if this behavior is documented somewhere in the TS documentation?

**Comment by Ethan-Arrowood** [comment] 2020-08-28 13:24
My thoughts with this now are that we may not have a perfect solution. One thing we could try is to actually define FastifyPluginAsync and FastifyPluginCallback as `function` on the fastify types side (rather than as a `type` or `interface`). I'm not sure how nicely that will work, but it might be worth a shot if it solves this issue for us.

**Comment by fox1t** [comment] 2020-08-28 14:24
Since the overload/intersection can't be used on the left side to infer the types on the right side
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1620916/91578373-5ae48980-e94a-11ea-84aa-61ad938bc3b9.png">

The solution already implemented is the best one: we need two different types for async and callback style. 👍

**Comment by lundibundi** [comment] 2020-09-14 19:46
I think this can be closed with https://github.com/fastify/fastify/pull/2554 being landed.

**Comment by Ethan-Arrowood** [comment] 2020-09-14 19:57
I agree!

**Closed by Ethan-Arrowood** 2020-09-14 19:57 UTC
