### ISSUE TITLE
@fastify/swagger-ui, how to use/see components/schema items?

### ISSUE THREAD

**Issue by diberry** [fastify/help#875] opened 2023-05-03 20:31 UTC
#### You have already researched for similar issues?
Yes - saw several questions around this but no resolution for this question.

#### What are you trying to achieve, or the steps to reproduce?

See a swagger displayed with schemas the same way https://editor.swagger.io/ does.

My source code: [https://github.com/diberry/azure-typescript-e2e-apps/tree/diberry/fastify-server-1/api-fastify-openapi-server](https://github.com/diberry/azure-typescript-e2e-apps/tree/diberry/fastify-server-1/api-fastify-openapi-server)

My openapi file with Person schema highlighted: [https://github.com/diberry/azure-typescript-e2e-apps/blob/diberry/fastify-server-1/api-fastify-openapi-server/openApiSchema.yml#L77](https://github.com/diberry/azure-typescript-e2e-apps/blob/diberry/fastify-server-1/api-fastify-openapi-server/openApiSchema.yml#L77)

#### What was the result you received?

I see the Person schema in swagger.io but not fastify's swagger-ui. 

![image](https://user-images.githubusercontent.com/41597107/236042177-6d0542d9-eb73-44f4-ad7e-81b14771cd31.png)

![image](https://user-images.githubusercontent.com/41597107/236042372-63d03962-8b91-4e04-b7c3-8bf3f26ef48c.png)

**Comment by agjs** [comment] 2023-11-13 10:26
@mcollina Hey Matteo. Any chance any of you guys have any idea? We are also trying to figure this out, but we can't seem to make it work.

@diberry Did you maybe manage to solve it already?

**Comment by mcollina** [comment] 2023-11-13 10:36
I have the individual schemas working inside [Platformatic DB](https://docs.platformatic.dev), check it out.

I'm not sure what's not working as expected in your code.

**Comment by mcollina** [comment] 2023-11-15 17:23
@diberry your code is not available anymore

**Comment by mcollina** [comment] 2023-11-15 17:23
@agjs can you uplodate a way to reproduce?

**Comment by agjs** [comment] 2023-11-15 17:26
> @agjs can you uplodate a way to reproduce?

Hey Matteo. I believe that the issue is related to the fact that the `Schemas` on the bottom of the Swagger UI only appear if the schemas are referenced using `$refs`. I can't fully confirm this yet, as this is the issue we had at my full time job, not Programmer Network, so I can get back to you on this.

But if I remember from a day or two ago, I saw someone somewhere having the same issue, and apparently, referencing schemas using $refs might fix it.

Cheers man

**Comment by mcollina** [comment] 2023-11-15 17:28
There is literally nothing to do then, minus mentioning this in the docs.

**Comment by agjs** [comment] 2023-11-15 17:28
> There is literally nothing to do then, minus mentioning this in the docs.

I'll give this a shot later on, so let's not close this yet. Once I confirm it, I'll ping you here again.

**Comment by agjs** [comment] 2023-11-15 17:39
> There is literally nothing to do then, minus mentioning this in the docs.

Alright, just added an example schema from the official documentation

```js
fastify.addSchema({
  $id: 'http://example.com/',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})
```

And `models` do appear:

<img width="1594" alt="Screenshot 2023-11-15 at 18 36 53" src="https://github.com/fastify/help/assets/7226555/727dfaeb-1d83-4dee-8d1f-aa042fd10a3e">

So yeah, I can confirm that that is the issue for sure. Or in simple words, something to add to the documentation:

"To ensure that models are correctly rendered at the bottom of the Swagger UI page, it's important to define your schemas using $refs through fastify.addSchema. Directly embedding JSON schemas within the schema property of your route definitions in Fastify may lead to them not being displayed in Swagger UI."

You can either put this inside the docs yourself @mcollina or I can do a PR, whatever you prefer.

**Comment by agjs** [comment] 2023-11-15 17:47
Opened a PR: https://github.com/fastify/fastify-swagger-ui/pull/101

**Comment by agjs** [comment] 2023-11-16 09:15
Let's close this one, @mcollina.

**Comment by mcollina** [comment] 2023-11-16 09:17
Thx!

**Closed by mcollina** 2023-11-16 09:17 UTC
