### ISSUE TITLE
http2 TLS Error inside a Kubernetes 

### ISSUE THREAD

**Issue by shankarregmi** [fastify/help#835] opened 2023-02-17 09:25 UTC
#### You have already researched for similar issues?
 Yes

#### What are you trying to achieve, or the steps to reproduce?

I am trying to create a simple http2 server using fastify
```js
import Fastify from 'fastify';

const app = Fastify({
   http2: true
});

// Routes
app.post('/events', async(request, reply) => {
  // some validation code
   eventHandler.publish(events);
   reply.code(200).send({ status: 'ok' });
});

app.listen(8000, '0.0.0.0');
```

**_As this service is running inside a Kubernetes cluster I didn't see any point of using `https`_**

Other microservice can now send `events` to this  service inside a cluster using a `http2` client. Which was working perfectly fine.:laughing: 

#### Problem:
Now We want to have the feature where some clients running outside of the Kubernetes Cluster will be able to send events using `http2`.

For that we created
- Kubernetes Service
- Kubernetes Ingress with `tls` --> `https://eventhandler.myapp.com/events`

We are using Traefik as a reverse proxy which is doing a TLS termination for us.

#### What did you expect?
I was expecting that Traefik would do the TLS termination and will forward the request to my backend service where
traefik will communicate with my pod through K8S service using `http://events-service:8000/`

#### What was the result you received?
But the result is not as expected;
:heavy_check_mark:  pod to pod communication is working with `http://event-service:8000`
❌ When the ingress is involved in between, service located in other cluster can not communicate using the endpoint: `https://eventhandler.myapp.com`

If I dig deeper using Traefik Logs, Traefik gets `502 Bad Gateway' caused by: EOF` and we don't have any logs in events Service
If I try to see the verbose output with `curl`, it says
```curl

* Trying XX.XXX.XXX.XXX:443...
* TCP_NODELAY set
* Connected to eventhandler.myapp.com (XX.XXX.XXX.XXX) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.myapp.com
*  start date: Jun 13 14:53:08 2022 GMT
*  expire date: Jun 13 14:53:08 2023 GMT
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x558ad245c310)
> HEAD / HTTP/2
> Host: eventhandler.myapp.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 500 
HTTP/2 500 
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< content-length: 21
content-length: 21
< date: Fri, 17 Feb 2023 09:21:53 GMT
date: Fri, 17 Feb 2023 09:21:53 GMT

< 
* Connection #0 to host eventhandler.myapp.com left intact
```

#### Context

* *node version*: 18.12.0
* *fastify version*: 3.28.0
* *os*: Ubuntu (Linux)

**Comment by climba03003** [comment] 2023-02-17 09:41
It looks like `Traefik` issue more than a `fastify` issue.
Can you provide any log from `fastify` side? 
If non of them exists, it means that the request is never been received from `fastify`.

**Comment by shankarregmi** [comment] 2023-02-17 09:49
I set the log level to 'debug' and still I don't see any request coming to my `fastify` app
```js
fastify({
	http2: true,
	logger: { level: "debug" },
})
```

**Comment by metcoder95** [comment] 2023-02-17 09:55
I'm not well-versed in `Traefik` but here I'm guessing you're having an issue with TLS termination. Traeffik in theory should end the TLS there and try to reach `fastify` using `h2c` (the non-encrypted version of HTTP/2). I suggest you verify that as it can be the negotiation is failing before even `fastify` is able to do something

**Comment by climba03003** [comment] 2023-02-17 09:57
I am closing this issue because I believe the issue is cause by `Traefik`.

You should check how `Traefik` work as a TLS proxy or reach out the community forum.
I see massive of the same issue from `Traefik` community forum. So, I maybe a common problem of it.

**Closed by climba03003** 2023-02-17 09:57 UTC

**Comment by shankarregmi** [comment] 2023-02-17 13:01
**UPDATE**
It was rather a missing annotation in Kubernetes Service, which has to do with plain text communication between traefik and service;

Fixed by adding annotations in Kubernetes service definition:
` traefik.ingress.kubernetes.io/service.serversscheme: h2c`
