### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Trufinol** [fastify/help#424] opened 2021-04-29 07:16 UTC
Hi. I'm using fastify as REST API. When page loads - multiple requests are sent and in one of them it always fails with an error
```js
\app\node_modules\fastify\lib\route.js:437
    if (err || i === functions.length) {
                               ^

TypeError: Cannot read property 'length' of undefined
    at next (\app\node_modules\fastify\lib\route.js:437:32)
    at preParsingHookRunner (\app\node_modules\fastify\lib\route.js:472:3)
    at runPreParsing (\app\node_modules\fastify\lib\route.js:419:5)
    at Object.routeHandler [as handler] (\app\node_modules\fastify\lib\route.js:379:7)
    at Router.lookup (\app\node_modules\find-my-way\index.js:339:14)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
````

I register all routes at server.js as follows
`fastify.register(require('./src/routes/index'));`

The content of src/routes/index looks like this
```js
module.exports = function (fastify, opts, next) {
    fastify.register(version);
    fastify.register(events);
    fastify.register(employees);
    fastify.register(machines);
    next();
}
```
The content of each route looks like this:
```js

module.exports = function (fastify, o, next) {
  fastify.get('/v2/api/events', { schema: { query: allEventsQuerySchema } }, getAllEvents);
  fastify.get('/v2/api/events/project', { schema: { query: projectEventsQuerySchema } }, getProjectEvents);
  fastify.post('/v2/api/events', createEvent);
  fastify.put('/v2/api/events/:id', updateEvent);
  fastify.delete('/v2/api/events/:id', deleteEvent);
  next();
}
```

It started to happen when I updated fastify from 2.13.1 to 3.15.0
Did I miss something in the changelog? Please help me with fixing this error. 

## Your Environment

- *node version*: 14.16.0
- *fastify version*: 3.15.0
- *os*: Windows

**Comment by mcollina** [comment] 2021-04-29 08:40
This looks weird, can you assemble a reproducible example?

**Comment by Eomm** [comment] 2021-04-29 08:47
Do you have some `preParsing` hooks?
Reading the stack trace it could be related to [this change](https://github.com/fastify/fastify/blob/main/docs/Migration-Guide-V3.md#changed-preparsing-hook-behaviour-2286) - or an external plugin that is not updated

**Comment by mcollina** [comment] 2021-04-29 11:16
I'd recommend debug step-by-step and diagnose the problems.

**Comment by Trufinol** [comment] 2021-04-29 18:57
One thing that I noticed is that it happens for one endpoint. When I remove that endpoint - an error is thrown on another endpoint, and so on.

- Update all of the plugins did not help. 
- It's not related to any of the plugins because I tried to turn all of them off - the issue persists.
- If `fastify-cors` plugin is disabled - then the app doesn't crash, but all requests end with 401 error due to cors. So it crashes when processing the request. 

Could it be because of some of the requests I end up with `res.send(data)` and some with `return data`?

**Comment by mcollina** [comment] 2021-04-29 18:59
I have literally no clue.

**Comment by Trufinol** [comment] 2021-04-30 05:53
I tried to change check at `fastify/lib/route.js:418` - add `reply.context.preParsing &&` - `exception is` resolved. 
```js
  if (reply.context.preParsing && reply.context.preParsing !== null) {
    preParsingHookRunner(reply.context.preParsing, request, reply, handleRequest)
  } else {
    handleRequest(null, request, reply)
  }
}
```
But then for some of the requests, CORS header is missing.

Tried to use `fastify-express + cors` approach - same result.

Any clues? =)

**Comment by jsumners** [comment] 2021-04-30 14:19
We really cannot help without a minimal reproduction. The best we can do is suggest setting a break point, invoking the condition, and then inspecting the state of the stack during the condition.

**Comment by MoSheikh** [comment] 2021-07-04 22:49
I just had this exact issue occur and I realized it was due to some errant await statements on my part. For example:

```
await reply.code(400).send()
```
This may not apply to your case at all but I came across this while searching and thought I'd suggest it!

**Comment by MoSheikh** [comment] 2021-07-04 23:20
I had this exact same issue and realized after far too long that it was a schema definition issue in my route declaration. I had put in an invalid json schema type.

**Comment by Eomm** [comment] 2021-07-05 06:02
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by MoSheikh** [comment] 2021-07-05 14:00
Apologies if it was unclear - I just commented the above after fixing my issue in case someone else was encountering a similar error. I was able to find and fix the issue myself and it was due to my error.

Thank you for offering the help, and I appreciate all your great work on this project!

**Comment by jason-formby-SM** [comment] 2021-08-05 18:06
I recently run into the same error. When I debug it, I get to [this line](https://github.com/fastify/fastify/blob/main/lib/route.js#L423) in routes.js:

`  if (reply.context.preParsing !== null) {`

For me, `reply.context.preParsing` is undefined, so the functions parameter passed to `preParsingHookRunner` is as well.

**Comment by mcollina** [comment] 2021-08-05 18:12
@jason-formby-SM could you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by jason-formby-SM** [comment] 2021-08-05 20:52
@mcollina

I'm working on private (not owned by me) code and experimenting with replacing express with fastify. I won't claim everything is done the right or best way, so it's entirely possible this is due to a misunderstanding on my part and/or incorrect implementation.

I'm working in Typescript, and using Jest & Supertest for unit tests. I don't get the issue when just running and connecting to localhost from a browser. I've only encountered it so far when running unit tests. I'm using ts-node, and ts-jest for running these.

I went through a sequence of making changes (!== -> !=), getting the same error elsewhere, and found two other spots where a strict equality check for null isn't catching undefined: reply.js:347, and handleRequest.js@63.

After I made those workarounds, I didn't get the issue when I ran the unit test.

I've tried to create a MRE, but I don't know if this is minimum enough, so I apologize if this is too much:

basic.test.ts 
```
import { responseStatusCheck, getResponse } from './test-helpers';

describe('basic request test', () => {

    it('should respond', async () => {

        const response = await getResponse();

        responseStatusCheck(response);
    });
});
```


test-helper.ts
```
import supertest, { Response } from 'supertest';
import { fastify, FastifyInstance } from 'fastify';

const fastifyApp = fastify({logger: true});

const createServer = async () : Promise<FastifyInstance> => {
     fastifyApp.post('/', async (_req, res) => {
        await res.send({message: "server is running..."});
    });
    return fastifyApp;
};

export async function getResponse()
: Promise<supertest.Test> {
    const request = {
        session: 'unit-test-session',
    };
    const app = await createServer();
    
    return supertest(app.server)
        .post('/')
        .send(request);
}

export function responseStatusCheck(
    actual: Response,
) : void {

    expect(actual.status).toBe(200);
}
```


jest.confg.js
```
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleDirectories: ["node_modules", "local_node_modules"],
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  },
};
```


tsconfig.json
```
{
    "extends": "@tsconfig/node14/tsconfig.json",
    "compilerOptions": {
      "outDir": "build",                        /* Redirect output structure to the directory. */
    }
}
```


package.json :
```
{
  "name": "fastify-test-app",
  "description": "",
  "version": "0.0.1",
  "author": "Jason Formby",
  "engines": {
    "node": "14"
  },
  "scripts": {
    "test": "jest --silent --detectOpenHandles",
    "test-v": "jest --verbose --detectOpenHandles"
  },
  "dependencies": {
    "@types/node": "^15.14.7",
    "fastify": "^3.20.1",
    "ts-node": "^10.1.0"
  },
  "devDependencies": {
    "@tsconfig/node14": "^1.0.1",
    "@types/jest": "^26.0.23",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.29.0",
    "@typescript-eslint/parser": "^4.29.0",
    "eslint": "^7.32.0",
    "eslint-config-google": "^0.14.0",
    "jest": "^27.0.4",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "tslib": "^2.3.0",
    "typescript": "^4.3.3"
  }
}
```

**Comment by mcollina** [comment] 2021-08-06 07:38
It looks like there is some incompatibilities with `supertest`. I would recommend to use `serve.inject()` instead (this is built-in).

**Comment by KrakerXyz** [comment] 2021-12-01 02:01
I was having the op's same error and like MoSheikh, it was due to user error on my part in setting up schema validations incorrectly.

Specifically, I was putting a json schema directly for the 'response' field without wrapping with an object that specifies the status code for the schema.

**Comment by kbychkov** [comment] 2022-08-11 07:59
Hi! I've just got the same issue after updating to fastify 4.4.0 from 3.x. I found that in my case the reason is `example` attribute in the schema. I extracted this to MRE:

```javascript
const fastify = require("fastify")();

fastify.register(require("@fastify/swagger"));

fastify.register((app, _, done) => {
  app.route({
    method: "GET",
    url: "/one",
    schema: {
      params: {
        type: "object",
        properties: {
          foo: {
            type: "string",
            example: "foo" // this string breaks the `two` route
          }
        }
      }
    },
    handler: () => "one"
  });

  app.route({
    method: "GET",
    url: "/two",
    handler: () => "two"
  });

  done();
});

fastify.ready(() => {
  fastify.swagger();
});

fastify.listen({ port: 8080 }, (err, address) => {
  console.log(`Server is now listening on ${address}`);
});
```

It will throw the error with fastify 4.4.0 and @fastify/swagger 7.4.1 but it works with fastify 3.29.1 and @fastify/swagger 6.1.0. Here is [the link to codesandbox](https://codesandbox.io/s/fastify-issue-424-9ifct) for convenience.

**Comment by mcollina** [comment] 2022-08-11 09:57
Very strangely, I couldn't reproduce the `Cannot read property 'length' of undefined` exception locally. @kbychkov the example you showed can be fixed by adding a custom keyword `example` to Ajv:

```js
const fastify = require(".")({
  ajv: {
    plugins: [
      function addExample (ajv) {
        ajv.addKeyword({
          keyword: "example",
          type: "string",
          schemaType: "string"
        })
      }
    ]
  }
});

fastify.register((app, _, done) => {
  app.route({
    method: "GET",
    url: "/one",
    schema: {
      params: {
        type: "object",
        properties: {
          foo: {
            type: "string",
            example: "foo" 
          }
        }
      }
    },
    handler: () => "one"
  });

  app.route({
    method: "GET",
    url: "/two",
    handler: () => "two"
  });

  done();
});

fastify.listen({ port: 3000 }, (err, address) => {
  if (err) { // very important
    console.error(err)
    process.exit(1)
  }
  console.log(`Server is now listening on ${address}`);
});
```

**Comment by kbychkov** [comment] 2022-08-15 11:00
Your example works but it slightly different from mine. Without using @fastify/swagger you're definitely should describe the `example` keyword. I suppose this package extends the JSON schema with new keywords and it worked correctly in v6.x but something might be changed since 7.x version 🤔

**Comment by kbychkov** [comment] 2022-08-16 10:14
Hmmm, you're right. Without `@fastify/swagger` I get the `Failed building the validation schema for GET: /one, due to error strict mode: unknown keyword: "example"` exception. But after I register `@fastify/swagger` the error disappers and I can't understand why 🤕 Anyway, thank you for the solution, adding the `example` keyword solves the problem.

**Closed** 2022-08-22 17:02 UTC
Labels: help wanted
