### ISSUE TITLE
Documentation: Image is broken on encapsulation page

### ISSUE THREAD

**Issue by ninadhatkar** [fastify/help#405] opened 2021-03-31 08:54 UTC
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?
Navigate to here: https://www.fastify.io/docs/latest/Encapsulation/ 

<img width="1043" alt="Screenshot 2021-03-31 at 2 16 12 PM" src="https://user-images.githubusercontent.com/832023/113116992-aa19d200-922b-11eb-8842-c9d9e96864f3.png">

#### What was the result you received?
The image is broken on the documentation page here: https://www.fastify.io/docs/latest/Encapsulation/

#### Context
* *os*: Mac, 
* *I am using chrome browser*:

This is an issue that is not related to fastify framework itself but related to the documentation site. I was not sure where to report hence opened this issue.

**Comment by mcollina** [comment] 2021-03-31 09:43
Closing as duplicate of https://github.com/fastify/website/issues/225.

Would you like to send a PR to fix this?

**Closed by mcollina** 2021-03-31 09:43 UTC
